config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :users, only: [:show]
  resources :events
  resources :event_attendings, only: [:create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
  validates :event_date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :event_attendings, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :event_attendings, source: :attendee
  scope :past, -> { where('event_date < ?', DateTime.now) }
  scope :upcoming, -> { where('event_date > ?', DateTime.now) }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: 'creator_id', dependent: :destroy
  has_many :event_attendings, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :event_attendings, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def create
    if EventAttending.where(attended_event_id: Event.find(params[:event_id]), attendee_id: current_user.id).exists?
      return
    end

    @event_attending = Event.find(params[:event_id]).event_attendings.build(attendee_id: current_user.id)

    redirect_to user_path(current_user[:id]) if @event_attending.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def index
    @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to event_path(@event[:id])
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:event_id])
  end

  def update
    @event = Event.find(params(:id))
    if @event.update
      redirect_to event_path(@event[:id])
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
    @attending_events = EventAttending.where(attended_event_id: Event.find(params[:id]))
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_path(current_user[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :details, :event_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @events = current_user.events
    @past_events = current_user.attended_events.past
    @upcoming_events = current_user.attended_events.upcoming
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%=form_with model: @event do |f|%>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details, autocomplete: "details" %>
  </div>

  <div class="field">
    <%= f.label :event_date %><br />
    <%= f.date_field :event_date,  autocomplete: "event_date" %>
  </div>



    <div class="actions">
    <%= f.submit "Update Event" %>
  </div>
  <% end %>
  

app/views/events/index.html.erb
<h1>List of events</h1>


<h2>Past events</h2>
<%@past_events.each do |event|%>

  <h4><%= event.title%></h4>
  <p><%=link_to "View details", event_path(event)%></p>
  <p><%=link_to "Attend", event_attendings_path(event_id: event.id), method: :post, action: :create%></p>
  <% end %>
<h2>Upcoming events</h2>
<%@upcoming_events.each do |event|%>

  <h4><%= event.title%></h4>
   <p><%=link_to "View details", event_path(event)%></p>
  <p><%=link_to "Attend", event_attendings_path(event_id: event.id), method: :post, action: :create%></p>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%=form_with model: @event do |f|%>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details, autocomplete: "details" %>
    <% @event.errors.full_messages_for(:details).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :event_date %><br />
    <%= f.date_field :event_date,  autocomplete: "event_date" %>
    <% @event.errors.full_messages_for(:event_date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>



    <div class="actions">
    <%= f.submit "Submit Event" %>
  </div>
  <% end %>
  

app/views/events/show.html.erb
<h1><%=@event.title%></h1>

    <p><%= @event.details%></p>

    <li><%= @event.event_date%></li>

<h2>Attendees of this event</h2>
   <ul>
    <% @attending_events.each do |event|%>
        <li><%= event.attendee.email %></li>
    <% end %>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>


  <body>
    <nav>   
      <ul>
        <li><%= link_to "All events", root_path %></li>
        <li><%= link_to "Create event", new_event_path %></li>
        
        <%if user_signed_in?%>
        <li><%= link_to "Your events", user_path(current_user) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>        
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1> Created Events</h1>

<% @events.each do |event|%>

    <h3><%= event.title%></h3>
    <p><%= event.details%></p>
    <p><%= link_to'Edit Event', edit_event_path(event_id: event.id) %></p>

    <p><%= link_to "Delete event", event_path(event), 
                    method: :delete, 
                    data: { confirm: "Are you sure you want to delete this event?" }  %></p>


<% end %>

<h1>Your attending events</h1>
<h2>Past events</h2>
<%@past_events.each do |event|%>
       
    <h3><%= event.title%></h3>
    <p><%= event.details%></p>
    <p><%= event.event_date%></p>

<% end %>
<h2>Upcoming events</h2>
<%@upcoming_events.each do |event|%>
       
    <h3><%= event.title%></h3>
    <p><%= event.details%></p>
    <p><%= event.event_date%></p>

<% end %>